use_frameworks!

target 'TMDbFramework_Example' do
  
  pod 'TMDbFramework', :path => '../'
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'SwiftyJSON'
  pod 'ChameleonFramework'

  target 'TMDbFramework_Tests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
    
  end
end
