use_frameworks!

target 'TMDbFramework_Example' do
  
  pod 'TMDbFramework', :path => '../'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'ChameleonFramework'

  target 'TMDbFramework_Tests' do
    inherit! :search_paths

    
  end
end
