coverage_service: cobertura_xml
output_directory: xml_report
xcodeproj: Example/TMDbFramework.xcodeproj
scheme: TMDbFramework-Example
workspace: Example/TMDbFramework.xcworkspace
source_directory: TMDbFramework/Classes
binary_basename: TMDbFramework
ignore:
  - '../*'
  - 'Example/*'
