coverage_service: html
output_directory: html
xcodeproj: Example/TMDbFramework.xcodeproj
scheme: TMDbFramework-Example
workspace: Example/TMDbFramework.xcworkspace
source_directory: TMDbFramework/Classes
binary_basename: TMDbFramework_Example
ignore:
  - '../*'
  - 'Pods/*'
  - 'Example/*'
